#!/usr/bin/env bash
# loops from 1 to 10

counter=0

while ((counter < 10))
do
	if ((counter == 3 ))
	then
		echo "bad luck"
	elif (( counter == 7 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
